version: '3.5'

services:
    epikcart:
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: epikcart
        entrypoint: sh -c "npm install --legacy-peer-deps && npm run build && composer update && php artisan migrate && apache2-foreground"
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html

    mysql:
        image: mysql
        container_name: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=epikcart
        ports:
            - 3308:3306
        volumes:
            - /home/ubuntu/mysql-demo:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        ports:
            - 8888:80
